version: "3.4"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jonaspik/node-app
    environment:
      PORT: 3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis
    container_name: redis

volumes:
  mongodbdata:
