version: "3.4"

services:
  nginx:
    ports:
      - 3000:80

  node-app:
    image: node-app
    build:
      context: .
      args:
        NODE_ENV: development
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
      MONGO_USER: admin
      MONGO_PASSWORD: password
      SESSION_SECRET: secret
    command: ["npm", "run", "dev"]
